### ISSUE TITLE
Put motion control into threads?

### ISSUE THREAD

**Issue by beniroquai** [hongquanli/octopi-research#4]
Hey, 

very nice software you created there! I adapted it to GRBL and a small Allied Vision USB3 camera in [our fork](https://github.com/beniroquai/octopi-research). 
One thing I noticed is, when I do some motion, the USB connection is blocking image display and also GUI readout. Do you think it's worth thinking about encapsulating it into threads too? All other compartments are already queued and threaded, right? 

Thanks!

**Comment by hongquanli** [comment]
Hi Benedict! Glad you like the software and are making use of it! And the Allied Vision cameras are nice! I also like their MIPI cameras that can be directly routed to the GPU on Jetsons.

Yes this part (using "open-loop" wait for motion to complete instead of receiving a motion complete flag from the MCU) is what I have been wanting to fix for a long time. I had prototyped an implementation in a different project (fluidic controller) and would like to copy that over this weekends - will keep you posted. The new implementation will also allow some error detection.

For now, depending on how you're using it, changing wait time to 0 (line 15-21 https://github.com/beniroquai/octopi-research/blob/master/software/control/_def.py) might be a simpler hack, before a proper implementation is put into place. What do you think?

**Comment by beniroquai** [comment]
Cool! Thanks a lot! I'm looking forward to have some boilerplate code from your side in the future to get it working on our end! :-)

**Comment by hongquanli** [comment]
Sorry it took so long. Most of the work happened in these two commits: https://github.com/hongquanli/octopi-research/commit/07691dafeb88e83ed74523b0cf0e186ba1291fd8, https://github.com/hongquanli/octopi-research/commit/0e035914c6a6826f169b358b2460b2c07a880876. And then more features and bug fixes since.

**Comment by beniroquai** [comment]
Great! I'll give it a go on the Jetson!  :-)
One off-topic question here: Did you ever play with "real-time" image processing on the Jetson's GPU (e.g. Tensorflow) within octopi?

**Comment by hongquanli** [comment]
A little bit. We'll do a lot more in the next few months for our malaria, TB and plankton work. The below characterization was using openCV written in C as python didn't support CUDA openCV. Rinni from our lab has just translated the code to python with CuPy, with similar performance. I can send a link soon. What are the image processing that you'd like to implement?
<img width="626" alt="jetson GPU acceleration" src="https://user-images.githubusercontent.com/9373466/144163625-61a43758-afeb-4074-aece-c7bcaf8adc87.png">
